include:
  - template: Security/SAST.gitlab-ci.yml
  - local: 'yml_configs/.frontend-test.yml'
 
stages:
   - build-test
   - test

build-frontend-code-job:
  stage: build-test  
  rules:
    - changes:
      - frontend/**/*
  script:
    - cd frontend
    - npm install
    - npm run build

